webtalk_init -webtalk_dir C:/Documents/Sophomore2/Digital_logic_and_digital_system/DLDS/docs/Experiments/Lab4/vend_machine/vend_machine.sim/sim_1/behav/xsim/xsim.dir/vend_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 10 21:44:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e35b3c71-d938-4495-9d52-709584d80faf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4759c74710314b46925fb7d38686124c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "101" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "125241700 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1660097195 -regid "" -xml C:/Documents/Sophomore2/Digital_logic_and_digital_system/DLDS/docs/Experiments/Lab4/vend_machine/vend_machine.sim/sim_1/behav/xsim/xsim.dir/vend_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Documents/Sophomore2/Digital_logic_and_digital_system/DLDS/docs/Experiments/Lab4/vend_machine/vend_machine.sim/sim_1/behav/xsim/xsim.dir/vend_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Documents/Sophomore2/Digital_logic_and_digital_system/DLDS/docs/Experiments/Lab4/vend_machine/vend_machine.sim/sim_1/behav/xsim/xsim.dir/vend_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
